---
- name: enable ovirt engine repositories
  yum:
    name: https://resources.ovirt.org/pub/yum-repo/ovirt-release44.rpm
    state: present

- name: enable module for javapackages-tools
  command: yum module -y enable javapackages-tools

- name: enable module for pki-deps 
  command: yum module -y enable pki-deps

- name: enable module for postgresql 
  command: yum module -y enable postgresql:12

- name: isntall ovirt engine 
  yum: 
    name: ovirt-engine
    state: latest 
