---
- name: deploying EPEL and updates 
  block: 
  - name: enable EPEL for major release {{ ansible_distribution_major_version }}
    dnf: 
      name: "epel-release"
      state: latest 
  - name: enable EPEL for major release {{ ansible_distribution_major_version }}
    dnf: 
      name: "epel-release"
      state: latest 
  when: ansible_distribution_major_version >= '8'

- name: deploying EPEL and updates 
  block: 
  - name: enable EPEL for major release {{ ansible_distribution_major_version }}
    yum: 
      name: "epel-release"
      state: latest 
  - name: enable EPEL for major release {{ ansible_distribution_major_version }}
    yum: 
      name: "epel-release"
      state: latest 
  when: ansible_distribution_major_version <= '7'

