- name: deploying EPEL and updates
  block: 
  - name: install fail2ban for major release {{ ansible_distribution_major_version }}
    dnf: 
      name: fail2ban
      state: latest 
  when: ansible_distribution_major_version >= '8'

- name: deploying EPEL and updates
  block: 
  - name: install fail2ban for major release {{ ansible_distribution_major_version }}
    yum: 
      name: fail2ban
      state: latest 
  when: ansible_distribution_major_version <= '7'

- name: deploy fail2ban config file template
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local

- name: enable and start fail2ban service
  service:
    name: fail2ban
    enabled: yes
    state: restarted

